############## SBF Modeling Parameters ##############

############################### Directory and File Selection Options ###############################
# NOTE: This section covers important information about how LBCreduce will find the images you want to model.

image_dir : '/Users/kirstencasey/real_image_tests/imfit_sbf' #'/Users/kirstencasey/background_subtraction_tests/single-exposure_output/sci/imfit_sbf' #'/Users/kirstencasey/m81blob_out/sci/lbc-reduce_testing'  # Where all the files needed for image reduction are located
out_dir :  '/Users/kirstencasey/real_image_tests/imfit_sbf' #'/Users/kirstencasey/background_subtraction_tests/single-exposure_output/sci/imfit_sbf' #'/Users/kirstencasey/m81blob_out/sci/lbc-reduce_testing' # Specify desired path of output directory. If None, defaults to 'lbcreduce_<date>_<time>' in same location as image_dir
model_fn : 'artpop_sersic_r.fits' #'random_position_mock_injected_sersic_tiltedplane_model_r_2_Sersic.fits' #'mean_stack_cutout_sersic_tiltedplane_model_r_2_Sersic.fits'
resid_fn : 'artpop_sersic_resid_r.fits' #'random_position_mock_injected_sersic_tiltedplane_resid_r.fits' #'mean_stack_cutout_sersic_tiltedplane_resid_r.fits' # If create_resid_from_model is True then this is the filename the created residual will be saved under
create_resid_from_model : False
orig_image_fn : 'noise_artpop_injected_r.fits' # This is ignored unless create_resid_from_model is True
model_summary_fn : #'blank_sky_near_star_mock_injected_sersic_tiltedplane_bestfit-params_r.txt' #'mean_stack_cutout_sersic_tiltedplane_bestfit-params_r.txt'
psf : 'lbcr.median_psf_298.fits'
num_iters : 50
overwrite : True # Allow lbcreduce to overwrite out_dir if it already exists?

############################### Other Common Options ###############################
# NOTE: These are other commonly-used options you may find useful to change depending on your needs.

color_name : 'r'
color_term :  0.0 #-0.0950107466670183
extinction : 0.053
zpt : 27.83783164207953
pixscale : 0.22400
exposure_time : 300.281 # seconds
gain : 1.75
ext : 0
logger_level : 'INFO' # What is the lowest-level output you want to see on the terminal (or in the logger file, if applicable)
log_to_file :  # Filename of output file for logger. Logger not output to file if no filename given

# Bestfit model results (ignored if model_summary_fn is provided)
radius : 221.02
xpos : 525.0
ypos : 525.0
ellip : -0.0926788
n : 0.52078
I_e : 7.434
pa : 9.53788
color : 1.2566041142595807

############################### SBF Options ###############################
# NOTE:

# SBF fitting
k_min : 0.05
k_max : 0.4
randomly_vary_k_limits : True
random_k_limit_deviation : 0.05
min_random_diff_between_kmin_kmax : 0.15
num_radial_bins : 45
use_sigma : False
plot_percentiles_min : 0.1
plot_percentiles_max : 99.9

# SBF masking
given_abs_mag_to_mask : -4
assumed_distance : 3.7 # Mpc

masking_sbf:
  randomly_vary_mask_radius : False
  fixed_frac_of_radius : 0.8 # Ignored if randomly_vary_mask_radius is True
  min_random_frac_of_radius : 0.7 # Ignored if randomly_vary_mask_radius is False
  max_random_frac_of_radius : 1.0 # Ignored if randomly_vary_mask_radius is False
  thresh : 5.0
  kern_sig : 1.0
  backsize : 15
  obj_rmin : 5
  grow_obj : 8.0
  randomly_vary_grow_obj : False
  random_growth_max_deviation : 1.5
  seg_rmin : 2000.0
