####### LBC Reduce Parameters #######

### Directory options ###
image_dir : 'test_raw_ims' # Where all the files needed for image reduction are located
out_dir : 'test_out' # Specify desired path of output directory. If None, defaults to 'lbcreduce_<date>_<time>' in same location as image_dir
overwrite : True # Allow lbcreduce to overwrite out_dir if it already exists?

### Other common options ###
ext : 1 # FITS file extension of imaging data
check_output : True # Do you want to check on the image processing steps as they happen or just trust that everything is working out okay?
notes : '' # These notes will be added to the image-production-details.txt file included in the output directory along with the other options that were used diring image processing
data_units : 'adu'

### Header IMAGETYP Keywords ###
bias_image_keyword : 'zero'
object_image_keyword : 'object'
dark_image_keyword : 'dark'
flat_image_keyword : 'flat'

### Other Header information ###
overscan_region : 'BIASSEC'
science_region : 'TRIMSEC'
lbc_red : 'LBC-RED'
lbc_blue : 'LBC_BLUE'

### Image Processing Steps ###
reduce_objects : True # Always true unless you just want to make master flats/bias images, stack pre-processed images, etc.
flat : True # Perform flat-fielding
overscan : True # Subtract overscan from object images
stack : True # Stack images of like-object files after processing
zero : True # Perform zero frame subtraction on object files
bias : True # Perform 2D bias subtraction on flat fields
dark : False # Perform dark subtraction

### File selection options ###
object :  # Object names you want included in image processing (excludes all others). OBJECT keyword in object image headers. (***Currently only works for ONE object***)
propid : # Proposal ID you want included in image processing (excludes all others). PROPID keyword in object image headers.(***Currently only works for ONE propid***)
glob_include : '*.fits' # Unix-style filename segment used to include files (eg. '*20191220*')
exclude :  # Filename segment (NOT UNIX-STYLE) used to exclude files (eg. '_OT.fits'). NOTE THIS IS DIFFERENT FROM THE UNIX-STYLE glob_include!! Do NOT add '*'s to the string to be excluded.


### Image Processing Options ###

# Combine images to make master flats, master bias images, etc.
# More info: https://ccdproc.readthedocs.io/en/latest/api/ccdproc.combine.html
combine_options:
  method : 'average'
  weights :
  scale :
  mem_limit : 16000000000.0
  clip_extrema : False
  nlow : 1
  nhigh : 1
  minmax_clip : False
  minmax_clip_min :
  minmax_clip_max :
  sigma_clip : True
  sigma_clip_low_thresh : 3
  sigma_clip_high_thresh : 3
  sigma_clip_func : 'median' # Options: median, mean
  sigma_clip_dev_func : 'mad_std' # Options: std, mad_std
  dtype :
  combine_uncertainty_function :

# Overscan subtract
# More info: https://ccdproc.readthedocs.io/en/latest/api/ccdproc.subtract_overscan.html
overscan_options:
  overscan_axis : 1
  fits_section :
  median : True
  model :
  add_keyword : True

# Overscan trim
# More info: https://ccdproc.readthedocs.io/en/latest/api/ccdproc.trim_image.html
trim_options:
  add_keyword : True
